<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AssessmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assessments = [
            [
                'farmer_name' => 'Rajesh Kumar',
                'region' => 'Punjab',
                'latitude' => 31.1471,
                'longitude' => 75.3412,
                'land_holding_size' => 5.2,
                'irrigation_source' => 'Tube Well',
                'cropping_pattern' => 'Rabi',
                'crop_grown' => 'Wheat',
                'well_depth' => 75.0,
            ],
            [
                'farmer_name' => 'Suresh Patel',
                'region' => 'Gujarat',
                'latitude' => 22.2587,
                'longitude' => 71.1924,
                'land_holding_size' => 3.8,
                'irrigation_source' => 'Canal',
                'cropping_pattern' => 'Kharif',
                'crop_grown' => 'Cotton',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Amit Singh',
                'region' => 'Uttar Pradesh',
                'latitude' => 26.8467,
                'longitude' => 80.9462,
                'land_holding_size' => 2.1,
                'irrigation_source' => 'Tube Well',
                'cropping_pattern' => 'Mixed',
                'crop_grown' => 'Sugarcane',
                'well_depth' => 35.0,
            ],
            [
                'farmer_name' => 'Ravi Reddy',
                'region' => 'Telangana',
                'latitude' => 18.1124,
                'longitude' => 79.0193,
                'land_holding_size' => 4.5,
                'irrigation_source' => 'Tank',
                'cropping_pattern' => 'Kharif',
                'crop_grown' => 'Paddy (Rice)',
                'well_depth' => 60.0,
            ],
            [
                'farmer_name' => 'Vikram Sharma',
                'region' => 'Madhya Pradesh',
                'latitude' => 22.9734,
                'longitude' => 78.6569,
                'land_holding_size' => 10.0,
                'irrigation_source' => 'Rainfed',
                'cropping_pattern' => 'Kharif',
                'crop_grown' => 'Soybean',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Mahendra Singh',
                'region' => 'Rajasthan',
                'latitude' => 26.9124,
                'longitude' => 75.7873,
                'land_holding_size' => 8.5,
                'irrigation_source' => 'Tube Well',
                'cropping_pattern' => 'Kharif',
                'crop_grown' => 'Pearl Millet (Bajra)',
                'well_depth' => 120.0,
            ],
            [
                'farmer_name' => 'Nitin Patil',
                'region' => 'Maharashtra',
                'latitude' => 19.7515,
                'longitude' => 75.7139,
                'land_holding_size' => 6.2,
                'irrigation_source' => 'Canal',
                'cropping_pattern' => 'Mixed',
                'crop_grown' => 'Sugarcane',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'H. R. Gowda',
                'region' => 'Karnataka',
                'latitude' => 12.9716,
                'longitude' => 77.5946,
                'land_holding_size' => 4.8,
                'irrigation_source' => 'Tube Well',
                'cropping_pattern' => 'Plantation',
                'crop_grown' => 'Coffee',
                'well_depth' => 90.0,
            ],
            [
                'farmer_name' => 'K. Selvam',
                'region' => 'Tamil Nadu',
                'latitude' => 10.7870,
                'longitude' => 79.1378,
                'land_holding_size' => 3.2,
                'irrigation_source' => 'River',
                'cropping_pattern' => 'Kharif',
                'crop_grown' => 'Paddy (Rice)',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Y. S. Rao',
                'region' => 'Andhra Pradesh',
                'latitude' => 16.5062,
                'longitude' => 80.6480,
                'land_holding_size' => 5.5,
                'irrigation_source' => 'Canal',
                'cropping_pattern' => 'Rabi',
                'crop_grown' => 'Maize',
                'well_depth' => 40.0,
            ],
            [
                'farmer_name' => 'Ram Pukar',
                'region' => 'Bihar',
                'latitude' => 25.0961,
                'longitude' => 85.3131,
                'land_holding_size' => 1.8,
                'irrigation_source' => 'Tube Well',
                'cropping_pattern' => 'Rabi',
                'crop_grown' => 'Wheat',
                'well_depth' => 28.0,
            ],
            [
                'farmer_name' => 'Subhas Bose',
                'region' => 'West Bengal',
                'latitude' => 22.9868,
                'longitude' => 87.8550,
                'land_holding_size' => 2.5,
                'irrigation_source' => 'River',
                'cropping_pattern' => 'Kharif',
                'crop_grown' => 'Paddy (Rice)',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Jagdev Singh',
                'region' => 'Haryana',
                'latitude' => 29.0588,
                'longitude' => 76.0856,
                'land_holding_size' => 7.4,
                'irrigation_source' => 'Canal',
                'cropping_pattern' => 'Rabi',
                'crop_grown' => 'Mustard',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Joseph Thomas',
                'region' => 'Kerala',
                'latitude' => 9.9312,
                'longitude' => 76.2673,
                'land_holding_size' => 1.5,
                'irrigation_source' => 'Rainfed',
                'cropping_pattern' => 'Plantation',
                'crop_grown' => 'Rubber',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Baruah Phukan',
                'region' => 'Assam',
                'latitude' => 26.2006,
                'longitude' => 92.9376,
                'land_holding_size' => 3.0,
                'irrigation_source' => 'Rainfed',
                'cropping_pattern' => 'Plantation',
                'crop_grown' => 'Tea',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Ramesh Vyas',
                'region' => 'Rajasthan',
                'latitude' => 26.2389,
                'longitude' => 73.0243,
                'land_holding_size' => 2.0,
                'irrigation_source' => 'Rainfed',
                'cropping_pattern' => 'Zaid',
                'crop_grown' => 'Watermelon',
                'well_depth' => null,
            ],
            [
                'farmer_name' => 'Vinay Shukla',
                'region' => 'Uttar Pradesh',
                'latitude' => 27.1767,
                'longitude' => 78.0081,
                'land_holding_size' => 3.5,
                'irrigation_source' => 'Tube Well',
                'cropping_pattern' => 'Rabi',
                'crop_grown' => 'Mustard',
                'well_depth' => 30.0,
            ],
            [
                'farmer_name' => 'Harish Shah',
                'region' => 'Gujarat',
                'latitude' => 23.0225,
                'longitude' => 72.5714,
                'land_holding_size' => 4.2,
                'irrigation_source' => 'Canal',
                'cropping_pattern' => 'Zaid',
                'crop_grown' => 'Cucumber',
                'well_depth' => null,
            ]
        ];

        foreach ($assessments as $assessment) {
            \App\Models\Assessment::create($assessment);
        }
    }
}
