@extends('layouts.app')

@section('title', 'New Assessment')

@section('content')
<div class="page-title">
    <h1>New Assessment</h1>
    <a href="{{ route('assessments.index') }}" class="btn" style="background: white; border: 1px solid var(--border-color); color: var(--text-main);">
        Back to Dashboard
    </a>
</div>

<div class="card">
    @if ($errors->any())
        <div class="alert" style="background-color: #fee2e2; color: #b91c1c; border: 1px solid #fca5a5;">
            <ul style="margin-left: 1.5rem;">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('assessments.store') }}" method="POST">
        @csrf
        <div class="grid-2">
            <div class="form-group">
                <label for="farmer_name" class="form-label">Farmer/Owner Name</label>
                <input type="text" id="farmer_name" name="farmer_name" class="form-control" value="{{ old('farmer_name') }}" required>
            </div>
            <div class="form-group">
                <label for="region" class="form-label">Region/District</label>
                <input type="text" id="region" name="region" class="form-control" value="{{ old('region') }}" required>
            </div>
        </div>

        <div class="form-group" style="margin-bottom: 2rem;">
            <label class="form-label" style="display: flex; align-items: center; gap: 0.5rem;">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                Select Location on Map
            </label>
            <p style="font-size: 0.875rem; color: var(--text-muted); margin-bottom: 0.5rem;">Click anywhere on the map to automatically fill in the latitude and longitude coordinates.</p>
            <div id="selection-map" style="width: 100%; height: 300px; border-radius: var(--radius-md); box-shadow: inset 0 0 0 1px var(--border-color); background-color: #e5e7eb;"></div>
        </div>

        <div class="grid-2">
            <div class="form-group">
                <label for="latitude" class="form-label">Latitude</label>
                <input type="number" step="any" id="latitude" name="latitude" class="form-control" value="{{ old('latitude') }}" required placeholder="e.g. 20.5937">
                <small style="color: var(--text-muted); font-size: 0.875rem;">Between -90 and 90</small>
            </div>
            <div class="form-group">
                <label for="longitude" class="form-label">Longitude</label>
                <input type="number" step="any" id="longitude" name="longitude" class="form-control" value="{{ old('longitude') }}" required placeholder="e.g. 78.9629">
                <small style="color: var(--text-muted); font-size: 0.875rem;">Between -180 and 180</small>
            </div>
        </div>

        <!-- Removed fields per request. They are now automatically generated by AI in the backend -->

        <div style="margin-top: 2rem; display: flex; justify-content: flex-end;">
            <button type="submit" class="btn btn-primary">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg>
                Save Assessment
            </button>
        </div>
    </form>
</div>
@endsection

@push('scripts')
<script>
    function initSelectionMap() {
        const center = { lat: 20.5937, lng: 78.9629 }; // Center of India
        const map = new google.maps.Map(document.getElementById("selection-map"), {
            zoom: 4,
            center: center,
            styles: [
                {
                    "featureType": "administrative",
                    "elementType": "geometry",
                    "stylers": [{"visibility": "off"}]
                }
            ],
            streetViewControl: false,
            mapTypeControl: false,
        });

        let currentMarker = null;

        // Auto-place marker if we already have coordinates
        const latInput = document.getElementById('latitude');
        const lngInput = document.getElementById('longitude');
        
        if (latInput.value && lngInput.value) {
            const pos = { lat: parseFloat(latInput.value), lng: parseFloat(lngInput.value) };
            currentMarker = new google.maps.Marker({
                position: pos,
                map: map,
                animation: google.maps.Animation.DROP
            });
            map.setCenter(pos);
            map.setZoom(7);
        }

        map.addListener('click', (e) => {
            const lat = e.latLng.lat();
            const lng = e.latLng.lng();
            
            // Update input fields automatically
            latInput.value = lat.toFixed(6);
            lngInput.value = lng.toFixed(6);

            // Flash inputs to show they were updated
            latInput.style.backgroundColor = 'var(--primary-light)';
            lngInput.style.backgroundColor = 'var(--primary-light)';
            setTimeout(() => {
                latInput.style.backgroundColor = '#fff';
                lngInput.style.backgroundColor = '#fff';
            }, 500);

            // Update or create marker
            if (currentMarker) {
                currentMarker.setPosition(e.latLng);
            } else {
                currentMarker = new google.maps.Marker({
                    position: e.latLng,
                    map: map,
                    animation: google.maps.Animation.DROP
                });
            }
        });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&callback=initSelectionMap" async defer></script>
@endpush
